### ISSUE TITLE
this project can't build in Qt5.9 or Qt5.13.0 

### ISSUE THREAD

**Issue by YHCH0413** [George-Sithole/Qttitude#1]
D:\DevelopToolKits\Qt\Qt5.9.8\Tools\mingw530_32\i686-w64-mingw32\include\c++\bits\random.h:87: error: static assertion failed: sorry, would be too much trouble for a slow result
  static_assert(__which < 0, /* needs to be dependent */
D:\DevelopToolKits\Qt\Qt5.9.8\Tools\mingw530_32\i686-w64-mingw32\include\c++\bits\random.h:117: error: no type named 'type' in 'struct std::__detail::_Select_uint_least_t<127, 1>'
            + std::__lg(__m) + 2>::type _Tp2;

**Comment by George-Sithole** [comment]
Apologies for the late reply
Thanks for raising this issue.

I have compiled the project in Qt5.12 (on linux) and Qt5.13 (windows) without problems.
I haven't tried it on Qt.5.9.

1. Is there more compile information. With the information provided its difficult for me to know where in the code the bug was generated. At the moment all I have to go with is that the error is raised in the mingw library random.h

2. Something else to try. Please delete the file Qttitude.pro.user and reconfigure the project.

George
